### ISSUE TITLE
Feat: Support Icon Shortcodes

### ISSUE THREAD

**Issue by aidenlx** [joethei/obsidian-link-favicon#1]
Hi! First of all, great work on Link Favicon! I'm the dev of [Icon shortcodes plugin](https://github.com/aidenlx/obsidian-icon-shortcodes), which provides Font Awesome, Remixicon icons out of the box, and allow user to import any custom icon they have. Adding support for icon shortcodes would help user a lot in case they need to use their custom icons. 

You can check here for details about its api: https://github.com/aidenlx/obsidian-icon-shortcodes#for-developer, and feel free to ask if you have any question :)

**Comment by joethei** [comment]
Hi, first of all thank you for this suggestion. 

From your type def I don't seem to be able to get a list of all icon names, which would be helpful for building a suggestion for configuring these icons.

**Comment by aidenlx** [comment]
indeed, my plugin have an EditorSuggest modal working in in editor that would activate when typing `:`, but that won't work on regular <input> element, maybe you can add a input box that only validate the shortcode and let user to get desired icon shortcode from editor. I'll expose some modal that would work outside of editor, but it may take some time

**Comment by joethei** [comment]
sure, going to implement this once v0.13 of obsidian has been released to the public(I am not an insider)

**Comment by aidenlx** [comment]
Good news! obsidian v0.13+ is publicly available for test and icon shortcode plugin is now available in the community plugin list. No rush if you don’t have time though, just sharing the news.

**Comment by joethei** [comment]
This is now available,  if your plugin is also installed.

**Comment by aidenlx** [comment]
> From your type def I don't seem to be able to get a list of all icon names, which would be helpful for building a suggestion for configuring these icons.

since v0.6.1, a new method `getIconFromUser` can open a modal to prompt user for icon selection. (make sure to check if it's available before calling it btw, you can do this by checking plugin version)

**Comment by joethei** [comment]
This is now implemented in v1.4.0
