### ISSUE TITLE
1.6.3 breaks dataview

### ISSUE THREAD

**Issue by chrisgrieser** [joethei/obsidian-link-favicon#12]
https://user-images.githubusercontent.com/73286100/154842900-d3cafd37-2402-432f-ab66-0138d2a63298.mov

**Comment by joethei** [comment]
This is interesting.
I see that you use links inside the tasks.
What is the format for those?

**Comment by chrisgrieser** [comment]
normal markdown links? or what do you mean? `[]()`

**Comment by joethei** [comment]
Yeah, that is what I meant, since I could not reproduce this previously.

Does the dataview result show up after a bit?
I was just away from the computer for a moment, and now they are there.

**Comment by chrisgrieser** [comment]
nope, stays that way for me :(

**Comment by chrisgrieser** [comment]
well, 1.4.4 is the last release that doesn't break anything for me? Strange. 🤔

**Comment by joethei** [comment]
You are still on the normal non insider build right?

**Comment by chrisgrieser** [comment]
yeah:

```text
macOS 12.0.1
Obsidian 0.13.23
```

**Comment by joethei** [comment]
That makes this even stranger,
The plugin still does it's job on normal files?

**Comment by chrisgrieser** [comment]
well, I haven't been only on 1.6.3 too long yet, but I didn't notice any other issue. Also, the problem didn't occur with 1.5.0 I think

**Comment by joethei** [comment]
I am not sure if this is even triggered by my plugin, but your recording does make it look so.
I disabled all plugins but dataview but the issue persists.
Very strange,😵

https://user-images.githubusercontent.com/7150512/154857058-990d0647-ea53-4caf-a1ff-9fcfb6212b73.mp4

(I did stop the recording before the last query has even been rendered)

**Comment by NomarCub** [comment]
Probably related to #14. It breaks for me the same way, also on Obsidian 0.13.23, on Windows.

**Comment by NomarCub** [comment]
This and #14 works for me now in the latest Obsidian version, v0.13.33.

**Comment by chrisgrieser** [comment]
can confirm, newest version does not break the plugin anymore.

**Comment by joethei** [comment]
Since this seems to be fixed for some reason, I am closing this issue.
