### ISSUE TITLE
Favicons don't work with dataview when using elinks

### ISSUE THREAD

**Issue by Obadiahcruz** [joethei/obsidian-link-favicon#13]
https://user-images.githubusercontent.com/22825246/155834144-2fac1159-f0ec-4bfb-83bf-d7460f8ae96d.mov

Is there a way to allow this to work? i use elinks and have dataview replace the urls with a custom name. but the favicons dont show up with elinks

**Comment by joethei** [comment]
I got this to work in Reading mode, but unfortunately not in Live Preview.
