### ISSUE TITLE
Reading view breaks

### ISSUE THREAD

**Issue by NomarCub** [joethei/obsidian-link-favicon#14]
![reading](https://user-images.githubusercontent.com/5298006/155870559-0c67c64b-4592-4d1d-8d60-8bca31b0f590.gif)

Similar errors occur when embedding notes in live preview and when using the dataview plugin.
I'm on Windows 10, Obsidian v0.13.23, the example is from the untouched Obsidian Help vault.

**Comment by BigbadHort** [comment]
it is for me too!

**Comment by joethei** [comment]
Does this still happen with the latest Obsidian version(0.13.32) ?
Because the error message complains about a thing that has been introduced with 0.13.25
(And it seems like I did not properly guard against this.)

**Comment by NomarCub** [comment]
It works for me now in v0.13.33.
