### ISSUE TITLE
GET 404

### ISSUE THREAD

**Issue by NomarCub** [joethei/obsidian-link-favicon#15]
![404](https://user-images.githubusercontent.com/5298006/155870926-ceea6da9-ccd8-4291-861f-9ca69c6fc306.gif)

The icon loads but there's a 404 error on console.

This is the link I used: `[link](https://www.earwolf.com)`. All providers are on default.
I'm on Windows 10, Obsidian v0.13.23, the example is from the untouched Obsidian Help vault.

**Comment by joethei** [comment]
This is because the default provider does not have the icon, and the fallback provider does have it.
This is to be expected.
