### ISSUE TITLE
Don't reload when links are unaffected

### ISSUE THREAD

**Issue by NomarCub** [joethei/obsidian-link-favicon#23]
Favicons reload when anything is modified (in addition to when new things coming into view in #22).

![reload](https://user-images.githubusercontent.com/5298006/158079029-1d2595e0-f6fd-49ca-9200-e29db5969e86.gif)

Even having heard the implementation reasonings in #22, I'm really skeptical that this is working as intended. Is a really long debouncing interval the best I can do? Couldn't the favicons only respond to their own links being changed, not anything in the document? Or at least the edited/active line/paragraph be checked before the reloading is initiated?

Scrolling unloaded documents already looks wonky in Obsidian so I guess #22 is as good as it will get, but I can't see why this one has to happen. What restrictions exactly do CodeMirror decorations have?

**Comment by joethei** [comment]
I only get the currently visible content, I don't know where there cursor currently is.
The content I get is also in a raw format, without any information if there is an icon already present.

There is some caching already present, but I had changed that a bit to solve #21.
Seems like I can either solve this or #21.
Will investigate more.

**Comment by NomarCub** [comment]
It's not a happy compromise, but I guess I'll just switch back to 1.6.3 in the meantime.
This problem doesn't exist there at all, and #22 is also noticeably faster there too, I guess due to no file caching. I'd take manual refreshing over this, really don't like distractions.

What changes in 1.7.0 necessitated the constant refreshing? Could that part be optionally turned off?

**Comment by joethei** [comment]
The refreshing is a side-effect of fixing #21, which seems to be a rare edge case.
