### ISSUE TITLE
Link Level Ignore

### ISSUE THREAD

**Issue by ChristinWhite** [joethei/obsidian-link-favicon#29]
**Request:** It would be really helpful if there was a way to disable a link icon on a link level in addition to the domain option that already exists. Perhaps something like `[Twitter|noicon](https://twitter.com/abraintool)` following the syntax used in a bunch of other plugins for setting parameters to specific items. 

**Why:** There are definitely times I want to exclude an icon, often if it's at the beginning of a list item where I don't want it conflicting visually with the bullet for things like [Minimal's checklist icons](https://minimal.guide/Block+types/Checklists) or if I want to use a different icon via [Icon Shortcodes](https://github.com/aidenlx/obsidian-icon-shortcodes).

Another example might be plugins that aren't especially compatible with Link Favicon yet such as [Simple Embeds](https://github.com/samwarnick/obsidian-simple-embeds) which will cause the favicon to be on its own line before the embed instead of directly preceding the link if you use the default place embeds above link setting. (I'll file a separate issue).

<img width="627" alt="CleanShot 2022-04-13 at 17 16 41@2x" src="https://user-images.githubusercontent.com/1746405/163289944-941c617d-03e1-472e-aac4-a1a54bb20e86.png">

**Comment by Trikzon** [comment]
I came to this repo's issues to ask exactly what ChristinWhite asked in this issue and #30.

For my use case, I prefer to use the Simple Embeds plugin with the link completely hidden. However, this plugin renders the favicon by itself when Simple Embeds hides the link causing unnecessary spacing. It would be great if there was a way to selectively hide the favicon in the way that ChristinWhite suggested.
