### ISSUE TITLE
Bug: When using `Adapt to theme`, plugin fails in Reading Mode

### ISSUE THREAD

**Issue by chrisgrieser** [joethei/obsidian-link-favicon#33]
yea well, so that was another round of debugging a lot... 🙈 

So, the plugin fails to show favicons when
1. The new `Adapt to theme` in `Appearance` is activated
2. you are in reading mode
3. then restart once

The following error appears in the console:

```text
Uncaught (in promise) TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
    at Gt.eval (plugin:link-favicon:9:1486)
    at Generator.next (<anonymous>)
    at eval (plugin:link-favicon:7:907)
    at new Promise (<anonymous>)
    at I (plugin:link-favicon:7:727)
    at Gt.setColorAttributes (plugin:link-favicon:9:1242)
    at Bt.eval (plugin:link-favicon:8:2675)
    at Generator.next (<anonymous>)
    at c (plugin:link-favicon:7:765)
```

**Comment by chrisgrieser** [comment]
in case it helps finding the issue, when I use the [System Dark Mode Plugin](https://obsidian.md/plugins?id=obsidian-system-dark-mode) instead of `adapt to theme`, the plugin works without issues

**Comment by NomarCub** [comment]
It's probably somewhat related, that when the theme is set to `Adapt to system` (and system happens to be dark) favicon colors are inverted. It happened already when switching between themes but it could be solved by reloading, but that doesn't work here.

**Comment by NomarCub** [comment]
I think the problem might be [here](https://github.com/joethei/obsidian-link-favicon/blob/master/src/main.ts#L117). `app.getTheme()` yields `'system'` on auto dark mode.

**Comment by joethei** [comment]
🤦‍♂️I forgot to check that when I investigated this earlier.
Will fix

**Comment by NomarCub** [comment]
When can we expect progress on the GitHub issues, @joethei? Could outside help make things faster? (Some of them, like the line I linked don't look like they would need much time to fix.)

**Comment by joethei** [comment]
I do have a fix for this one ready, currently doing other fixes/refactors for some other issues.
Currently, fixing #35.
Given the scope of the refactor I will probably not accept PR's at the moment.

**Comment by NomarCub** [comment]
Hi @joethei!
Sorry to bother you, but this plugin is really important in my workflows and the issues still persist. When can we expect progress on this plugin?
