### ISSUE TITLE
Too many console logs

### ISSUE THREAD

**Issue by NomarCub** [joethei/obsidian-link-favicon#42]
I have basically every website in my note logged to console, tens of log messages just by scrolling a little. They clog up the console if I try to debug other things.
It's this line here: https://github.com/joethei/obsidian-link-favicon/blob/master/src/IconAdder.ts#L30
I should mention the comment above suggests this should only happen if the link has no protocol, but the links are all proper https:// links from big websites, so something seems off.

**Comment by joethei** [comment]
ooops, forgot to remove that one.

The comment is for the line below

**Comment by joethei** [comment]
will remove it in the next version, probably tomorrow or later today

**Comment by NomarCub** [comment]
I also found this typo in the readme: `.external-link.external-link.external-link`
