### ISSUE TITLE
Icons not showing in edit mode

### ISSUE THREAD

**Issue by hidegh** [joethei/obsidian-link-favicon#55]
1. make icons visible also in edit mode (default mode, except dashboard)
2. ...also the setting below makes me think it should work in edit mode:
![image](https://user-images.githubusercontent.com/6331063/222168604-9007d474-4de6-40c4-af4d-95a1398b266a.png)

**Comment by ituri** [comment]
Same here.

**Comment by joethei** [comment]
It should now work properly again.
