### ISSUE TITLE
[FR] Add an option to keep icons offline

### ISSUE THREAD

**Issue by AaronKnowls** [joethei/obsidian-link-favicon#58]
Would it be possible to keep favicons cached so they don't need to load every time? I hope this makes sense.

Thank you for your plugin, it's very useful.

**Comment by guihasparyk** [comment]
> Or to same them to the vault, as I would also like to use them in for example a database view.

That's an awesome Ideia indeed. 👏🏻👏🏻

**Comment by YousufSSyed** [comment]
@AaronKnowls I recommend renaming this issue to "Add an option to keep icons offline and not have to re-download them on every page load." What do u think?

**Comment by joethei** [comment]
This FR does not make much sense to me.

Favicons are already cached for one month,

**Comment by YousufSSyed** [comment]
@joethei Obsidian's philosophy and one of their selling points is being offline first, all your notes and entire vault is offline. What if you were offline and that one month passed, then would the favicons be gone? Adding an option to keep them offline would add peace of mind for users, if they go offline then they don't have to worry about already downloaded favicons from going away.

@AaronKnowls Can u reopen the issue?

**Comment by YousufSSyed** [comment]
@AaronKnowls Would need to clarify, but I think they meant keeping them stored when he said cached.

I think you should make it an opt-in feature. There are many users including myself that don't use Obsidian Sync.
