### ISSUE TITLE
Wrong favicon placement in todo lists

### ISSUE THREAD

**Issue by eleanorkonik** [joethei/obsidian-link-favicon#6]
this is not where those icons are supposed to be 😅 

![image](https://user-images.githubusercontent.com/75856959/148103520-0940925c-79e1-4d3c-bc51-17e26430e327.png)

Screenshot is from primary but behavior occurs on sanctum & default theme.

**Comment by joethei** [comment]
How did I not have this as a test case 🤣
Well, has been fixed in the next update.(will be released shortly)
