### ISSUE TITLE
Remove Console logging

### ISSUE THREAD

**Issue by usernotnull** [joethei/obsidian-link-favicon#66]
The plugin outputs the content of opened files each time it runs in the console.

**Comment by YousufSSyed** [comment]
I almost wrote this myself, this makes writing console code and debugging other plugins frustrating.

**Comment by Aetherinox** [comment]
This definitely needs done. Working on dataview queries and every single line was being printed to console. Had to disable the plugin.

**Comment by YousufSSyed** [comment]
@joethei Do u have thoughts on how to prevent this in the future, perhaps a system or way to remove `console.log()` statements before compiling and publishing new plugin versions. This was pretty frustrating to deal with, turning the plugin and and off, when I want to debug my CustomJS in the console.
