### ISSUE TITLE
Bug on mobile/android: Plugin failed to load ...

### ISSUE THREAD

**Issue by avirosso** [joethei/obsidian-link-favicon#7]
On mobile/android it's possible to install, but not to 'activate' the plugin (error message: "Failed to load plugin link-favicon")

**Comment by joethei** [comment]
What version are you using?
The plugin only works in obsidian versions after 0.13.14, which is not released publicly for mobile yet.

**Comment by avirosso** [comment]
On mobile/android:
- obsidian version "1.0.5" (there is no newer version in playstore available)
- plugin version: "1.4.4"

**Comment by joethei** [comment]
Not sure why you were able to install that version of the plugin as that is for the live preview version(which is only available on desktop so far)
I don't know how to fix this, so you would need to wait until live preview has been released to mobile or  install v1.2.2 of this plugin as that is the last mobile compatible version.

**Comment by joethei** [comment]
The newest version might have fixed this issue,
If it did not please be patient and wait for the release of live preview for mobile.

**Comment by avirosso** [comment]
Thanks, but again I've got the error message "Failed to load plugin link-favicon" (plugin version: "1.5.0" / obsidian version "1.0.5"). So I have to wait for the new obsidian mobile release with live preview ...

**Comment by joethei** [comment]
After some time tinkering on another issue, I also fixed this one finally.

**Comment by avirosso** [comment]
Thanks!
