### ISSUE TITLE
Space character getting automatically deleted in Obsidian Tables when Link Favicon plugin is enabled

### ISSUE THREAD

**Issue by benjithompson** [joethei/obsidian-link-favicon#71]
Plugin Version: 1.8.4
Obsidian Version 1.5.4

### Issue 

In **Live Preview** mode, typing a space within a table cell will automatically get deleted.

### Expected 

When typing a space character in a table, it should not be deleted.

### Reproduction Steps 

1. Create a Table in a note 
2. While in Live Preview mode, type a "space" character in an empty cell, or after existing text 
3. Observe that the space gets deleted within a second of being typed.

NOTE: This cannot be reproduced if this plugin is disabled.

**Comment by joethei** [comment]
I cannot reproduce, do you have any other plugins enabled?

**Comment by benjithompson** [comment]
No other plugins are installed. I just created a new vault, and reproduced by only installing this one plugin:
![image](https://github.com/joethei/obsidian-link-favicon/assets/4298800/af49df63-6409-4963-8b27-757e87e0d015)

A simple table example has the issue in the first entry of text 'asdf' followed by a space character:
![image](https://github.com/joethei/obsidian-link-favicon/assets/4298800/735be6e9-81e6-4b2c-abf5-0bfc0c510920)


This is using the newest insider version of Obsidian.

**Comment by joethei** [comment]
You should be able to reproduce this issue without plugins too.
This is a bug in the application itself, and we (the Obsidian team) know what is causing it.

**Comment by benjithompson** [comment]
Interesting. I haven't seen it happen without this plugin enabled, but good to know. I'll check again if the fix is listed on an upcoming insider release. Thanks!
