### ISSUE TITLE
Meduim favicon invisible? 

### ISSUE THREAD

**Issue by eleanorkonik** [joethei/obsidian-link-favicon#8]
In both light and dark modes, I can't see the favicon for Medium sites. 

![image](https://user-images.githubusercontent.com/75856959/151544145-c0aa8013-96da-45e7-aff7-168a3094b580.png)

![image](https://user-images.githubusercontent.com/75856959/151544172-909c899f-b35a-496a-a114-12e635265b21.png)

The link goes here, for what it's worth: https://birrellwalsh.medium.com/obsidian-data-without-fences-58f3dcdc1d10

**Comment by joethei** [comment]
Seems like the small default favicon on medium is broken.

You can see here with another medium site that the small one is not rendering : 
![](https://i.joethei.space/TD1ElzCQ0o.png)
(screenshot from my instance of: https://github.com/mat/besticon)

Both google and duckduckgo use this broken favicon, with the other providers this is working.

**Comment by joethei** [comment]
I added a little button in the settings that should help debug this kind of issue in the future.
